"""Builds notebooks/01_governance_analysis.ipynb from scratch using nbformat.
Run once to generate the notebook; then execute it with nbconvert --execute --inplace.
"""
import nbformat as nbf
import os

nb = nbf.v4.new_notebook()
cells = []

def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))

def code(text):
    cells.append(nbf.v4.new_code_cell(text))

md("""# Governance Framework — Executed Analysis

This notebook runs directly against the live warehouse (`data/warehouse/governance.duckdb`) and every cell below produces real output from that run — nothing here is asserted without a query backing it.

**Read this first:** all data in this warehouse is synthetic, generated by `src/pipeline.py` with a fixed random seed, reseeded relative to the date the pipeline was last run. The patterns found below (DS-003, DS-012, the SLA inversion) are real behaviors of this specific pipeline run, and the analytical technique used to find them generalizes to real data — but the underlying data itself is not sourced from a real banking system. See `project_metrics.md` for the full limitations statement.""")

code("""import duckdb
import pandas as pd

conn = duckdb.connect('../data/warehouse/governance.duckdb', read_only=True)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 140)""")

md("## 1. Understanding the Data")

code("""conn.execute(\"\"\"
    SELECT category, regulatory_criticality, COUNT(*) as dataset_count
    FROM data_inventory
    GROUP BY category, regulatory_criticality
    ORDER BY category
\"\"\").df()""")

code("""conn.execute(\"\"\"
    SELECT dataset_id, COUNT(*) as tests_run,
        SUM(CASE WHEN status='Fail' THEN 1 ELSE 0 END) as fails,
        ROUND(100.0*SUM(CASE WHEN status='Fail' THEN 1 ELSE 0 END)/COUNT(*),1) as fail_rate_pct
    FROM control_test_results
    GROUP BY dataset_id
    ORDER BY fail_rate_pct DESC
\"\"\").df()""")

code("""conn.execute(\"\"\"
    SELECT status, COUNT(*) as n, ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER (),1) as pct
    FROM control_test_results GROUP BY status
\"\"\").df()""")

md("""## 2. Finding Patterns

Four pattern queries, run directly against live data.""")

md("### 2a. Trust score vs. watchlist status by domain")

code("""conn.execute(\"\"\"
    SELECT dts.domain, dts.trust_score, dts.trust_category,
        count(*) filter (where dw.watchlist_status='Watchlist') as n_watchlist,
        count(*) filter (where dw.watchlist_status='Monitor') as n_monitor
    FROM domain_trust_scores dts
    LEFT JOIN data_inventory di ON di.domain = dts.domain
    LEFT JOIN dq_watchlist dw ON dw.dataset_id = di.dataset_id
    GROUP BY dts.domain, dts.trust_score, dts.trust_category
    ORDER BY dts.trust_score DESC
\"\"\").df()""")

md("### 2b. Control failure rate by category")

code("""conn.execute(\"\"\"
    SELECT cr.category, COUNT(*) as total_tests,
        SUM(CASE WHEN ctr.status='Fail' THEN 1 ELSE 0 END) as failures,
        ROUND(100.0*SUM(CASE WHEN ctr.status='Fail' THEN 1 ELSE 0 END)/COUNT(*),1) as fail_rate
    FROM control_test_results ctr
    JOIN control_rulebook cr ON ctr.rule_id = cr.rule_id
    GROUP BY cr.category ORDER BY fail_rate DESC
\"\"\").df()""")

md("### 2c. SLA breach rate by severity — the headline secondary pattern")

code("""conn.execute(\"\"\"
    SELECT severity, COUNT(*) as total,
        SUM(CASE WHEN sla_breach THEN 1 ELSE 0 END) as breached,
        ROUND(100.0*SUM(CASE WHEN sla_breach THEN 1 ELSE 0 END)/COUNT(*),1) as breach_rate,
        SUM(CASE WHEN status='Resolved' THEN 1 ELSE 0 END) as ever_resolved,
        ROUND(100.0*SUM(CASE WHEN status='Resolved' THEN 1 ELSE 0 END)/COUNT(*),1) as pct_ever_resolved
    FROM remediation_tickets
    GROUP BY severity ORDER BY breach_rate DESC
\"\"\").df()""")

md("""**Counterintuitive result:** High-severity tickets (3-day SLA) breach at 73.3%, *higher* than Critical (1-day SLA) at 52.6%. The `pct_ever_resolved` column shows why: only 13.3% of High tickets have ever been resolved at all, vs. 31.6% of Critical — the gap isn't speed (both average 1.0 day to resolve once someone starts), it's that High tickets get worked far less often in the first place.""")

md("### 2d. Watchlist priority vs. actual failure volume")

code("""conn.execute(\"\"\"
    SELECT dw.dataset_id, dw.watchlist_status, dw.priority,
        COUNT(ctr.test_id) as total_tests,
        SUM(CASE WHEN ctr.status='Fail' THEN 1 ELSE 0 END) as fails
    FROM dq_watchlist dw
    JOIN control_test_results ctr ON ctr.dataset_id = dw.dataset_id
    GROUP BY dw.dataset_id, dw.watchlist_status, dw.priority
    ORDER BY fails DESC
\"\"\").df()""")

md("""## 3. The Headline Finding — DS-003: 100% Failure, Still "Trusted"

Risk Exposure (DS-003) failed **every one of its 150 control tests** over the full 30-day window. Its domain (Risk) is nonetheless scored 94.1/100, "Trusted" — a direct contradiction worth digging into.""")

code("""conn.execute(\"\"\"
    SELECT dataset_id, COUNT(*) as total_tests,
        SUM(CASE WHEN status='Fail' THEN 1 ELSE 0 END) as fails,
        ROUND(100.0*SUM(CASE WHEN status='Fail' THEN 1 ELSE 0 END)/COUNT(*),1) as fail_rate,
        ROUND(AVG(control_effectiveness),1) as avg_effectiveness
    FROM control_test_results
    WHERE dataset_id = 'DS-003'
    GROUP BY dataset_id
\"\"\").df()""")

code("""conn.execute(\"\"\"
    SELECT ctr.rule_id, cr.rule_name, cr.threshold, cr.severity,
        ROUND(AVG(ctr.control_effectiveness),2) as avg_eff, COUNT(*) as n_tests,
        SUM(CASE WHEN ctr.status='Fail' THEN 1 ELSE 0 END) as fails
    FROM control_test_results ctr
    JOIN control_rulebook cr ON cr.rule_id = ctr.rule_id
    WHERE ctr.dataset_id = 'DS-003'
    GROUP BY ctr.rule_id, cr.rule_name, cr.threshold, cr.severity
\"\"\").df()""")

md("""**Why this happens:** every one of DS-003's 5 controls averages 94.8–95.1% effectiveness — high in absolute terms, but just under each rule's 98–100% threshold, so every single test is classified `Fail`. The Data Trust Score formula averages continuous `control_effectiveness`, not binary pass/fail outcomes, and DS-003 is only "Monitor" status (1-point penalty) rather than "Watchlist," so the 100% fail rate barely dents the score. A dataset can fail literally every test it runs and still be labeled "Trusted."

**Proposed fix (demonstrated in Section 6 below):** a binary floor — any dataset with a 100% fail rate in its trailing 7-day window is capped at "At Risk" regardless of average effectiveness.""")

md("""## 4. Where the Framework Is Too Strict — DS-012 False Positive

The opposite failure mode: a near-zero absolute change classified as a severe alert.""")

code("""# The stored *_early columns are rounded to 2dp for display. The pipeline's own watchlist_reason
# is computed from the UNROUNDED value - so read the reason text, don't recompute from the column.
conn.execute(\"\"\"
    SELECT dataset_id, duplicate_rate_early AS early_rounded_for_display,
           duplicate_rate_recent, duplicate_rate_trend, watchlist_reason
    FROM dq_watchlist WHERE dataset_id = 'DS-012'
\"\"\").df()""")

code("""# Recover the TRUE unrounded baseline from the pipeline's own reported percentage,
# and check whether the max(x, 0.01) division-guard floor actually engaged.
import re
ds, recent, reason = conn.execute(\"\"\"
    SELECT dataset_id, duplicate_rate_recent, watchlist_reason
    FROM dq_watchlist WHERE dataset_id='DS-012'
\"\"\").fetchone()
pct = float(re.search(r'Duplicate rate increased ([\\d.]+)%', reason).group(1))
true_early = recent / (1 + pct/100)
print(f"reported by pipeline : {pct}%")
print(f"recomputed from the ROUNDED column: {((recent-0.01)/max(0.01,0.01))*100:.1f}%   <-- wrong by ~107pp")
print(f"true unrounded baseline           : {true_early:.5f}")
print(f"absolute move                     : {recent-true_early:.3f} percentage points")
print(f"did the max(x,0.01) floor engage? : {true_early < 0.01}")""")

code("""# Does that floor engage anywhere at all, on any of the three signals?
conn.execute(\"\"\"
    SELECT MIN(duplicate_rate_early) AS min_dup_early,
           MIN(null_rate_early) AS min_null_early,
           MIN(control_failure_rate_early) AS min_ctrl_early
    FROM dq_watchlist
\"\"\").df()""")

md("""A **0.129 percentage-point** move (0.0108% → 0.14%) on a monthly-refreshed dataset is reported as a **1192.9% increase** — the largest single movement on the entire watchlist. DS-003 (Section 3) shows the framework too lenient (total failure, still "Trusted"); DS-012 shows it too strict (a non-event, flagged loudest). Same class of formula problem, opposite ends.

Two corrections worth recording, since the first pass at this got both wrong:

1. **1,192.9%, not 1,300%.** Recomputing from the stored `duplicate_rate_early` column gives 1,300% — but that column is rounded to 2dp. The pipeline's own `watchlist_reason`, computed from the unrounded value, says 1,192.9%. Deriving a metric from a rounded intermediate rather than from source produced an answer ~107 percentage points off that silently disagreed with the project's own `COMPREHENSIVE_PROJECT_REPORT.md`.
2. **The `max(x, 0.01)` floor never fired.** The true baseline (0.01083) is *above* it — and per the cell above, the minimum early value across all three signals and all 13 datasets never drops below 0.01, so the floor doesn't engage anywhere in this data. The cause is percentage-change-on-a-near-zero-baseline generally; the floor is a latent version of the same hazard, not the active one.""")

md("## 5. Degenerate Metric Proof")

code("""conn.execute(\"\"\"
    SELECT dataset_id, COUNT(DISTINCT rule_id) as controls_assigned,
        ROUND(100.0*COUNT(DISTINCT rule_id)/30,1) as pct_of_30_rule_catalog
    FROM control_test_results GROUP BY dataset_id ORDER BY pct_of_30_rule_catalog DESC
\"\"\").df()""")

code("""conn.execute("SELECT * FROM governance_maturity").df()""")

md("""Per-dataset control coverage actually *varies* (6.7%–26.7% of the 30-rule catalog) — that is not the degenerate metric. The genuinely degenerate value is `governance_maturity.control_coverage`, a single enterprise-level constant (always 100.0, since all 13 datasets have at least one control assigned) alongside `audit_completeness` (hardcoded 100.0). Two of the four weighted inputs to Governance Maturity cannot move regardless of what actually happens operationally.""")

md("## 6. What-If Scenarios")

md("### 6a. Enterprise trust score with watchlist/monitor penalty removed")

md("""The enterprise score is the *mean of the per-domain scores*, and each domain score is
`avg_control_effectiveness - 3*watchlist_count - 1*monitor_count`. So "what if every watchlist and
monitor flag were cleared?" = the mean of the per-domain `avg_control_effectiveness`, with no penalty
subtracted. Computing it that way (rather than as a flat average over raw test rows) is what makes it
directly comparable to the stored enterprise score.""")

code("""conn.execute(\"\"\"
    SELECT ROUND(AVG(avg_control_effectiveness),1) AS enterprise_score_if_no_penalty
    FROM domain_trust_scores
    WHERE domain <> 'Enterprise (Overall)'
\"\"\").df()""")

code("""conn.execute("SELECT domain, trust_score FROM domain_trust_scores WHERE domain='Enterprise (Overall)'").df()""")

md("Current enterprise score 90.6 vs. 93.9 with the watchlist/monitor penalty zeroed out — a real but modest 3.3-point ceiling on what resolving every open issue could buy today (both endpoints remain \"Trusted\").")

md("### 6b. Demonstrate the DS-003 fix — binary floor")

code("""conn.execute(\"\"\"
    SELECT dts.domain, dts.trust_score as current_score, dts.trust_category as current_category,
        fr.total_fail_rate,
        CASE WHEN fr.total_fail_rate = 1.0 THEN 0 ELSE dts.trust_score END as fixed_score,
        CASE WHEN fr.total_fail_rate = 1.0 THEN 'At Risk' ELSE dts.trust_category END as fixed_category
    FROM domain_trust_scores dts
    JOIN data_inventory di ON di.domain = dts.domain
    JOIN (
        SELECT dataset_id, ROUND(1.0*SUM(CASE WHEN status='Fail' THEN 1 ELSE 0 END)/COUNT(*),3) as total_fail_rate
        FROM control_test_results GROUP BY dataset_id
    ) fr ON fr.dataset_id = di.dataset_id
    WHERE dts.domain = 'Risk'
\"\"\").df()""")

md("Under the binary floor, Risk domain's score flips from **94.1 \"Trusted\" → 0.0 \"At Risk\"** — an executed result, not a hypothetical.")

md("### 6c. Demonstrate the DS-003 fix — failure-streak escalation")

code("""conn.execute(\"\"\"
    WITH chronic AS (
        SELECT ctr.dataset_id, ctr.rule_id, cr.severity, cr.rule_name,
            COUNT(*) as failure_count
        FROM control_test_results ctr
        JOIN control_rulebook cr ON cr.rule_id = ctr.rule_id
        WHERE ctr.status='Fail'
        GROUP BY ctr.dataset_id, ctr.rule_id, cr.severity, cr.rule_name
        HAVING COUNT(*) >= 27
    )
    SELECT dataset_id, rule_id, rule_name, failure_count, severity as current_severity,
        CASE severity
            WHEN 'Low' THEN 'Medium'
            WHEN 'Medium' THEN 'High'
            WHEN 'High' THEN 'Critical'
            ELSE 'Critical'
        END as escalated_severity
    FROM chronic
    ORDER BY failure_count DESC, dataset_id
\"\"\").df()""")

md("33 dataset-rule pairs failed 27-30 of the last 30 days. Under a \"7+ consecutive days → escalate one severity tier\" rule, most Medium/High rules above would jump to High/Critical — currently every one of these generates the same single ticket regardless of how long the failure has persisted (see `sql/v2_rebuild/SQL_COMPARISON.md` Edge Case 4).")

md("### 6d. Trust score formula vs. a simpler alternative")

code("""conn.execute(\"\"\"
    WITH bounds AS (SELECT max(test_date) as max_date FROM control_test_results),
    recent AS (
        SELECT r.*, di.domain FROM control_test_results r
        JOIN data_inventory di ON di.dataset_id = r.dataset_id
        -- >= matches v1's inclusive 7-day window; see sql/v2_rebuild/SQL_COMPARISON.md file 03
        WHERE r.test_date >= (SELECT max_date FROM bounds) - INTERVAL 7 DAY
    ),
    simple AS (
        SELECT domain, ROUND(100.0*SUM(CASE WHEN status='Pass' THEN 1 ELSE 0 END)/COUNT(*),1) as simple_compliance_rate
        FROM recent GROUP BY domain
    )
    SELECT dts.domain, dts.trust_score as current_formula_score, dts.trust_category as current_category,
        s.simple_compliance_rate
    FROM domain_trust_scores dts
    LEFT JOIN simple s ON s.domain = dts.domain
    ORDER BY dts.trust_score DESC
\"\"\").df()""")

md("""The divergence is stark for some domains: Risk (94.1 "Trusted") and Product (96.9 "Trusted") both show **0.0%** simple pass/fail compliance; Customer (93.8 "Trusted") shows 13.6%. Other domains hold up better under both views (Finance: 98.9 vs. 90.6%). Neither formula is objectively correct — the current weighted formula is more forgiving of near-miss thresholds and factors in early-warning trend data the simple version ignores entirely, but that forgiveness is exactly what let DS-003 score "Trusted." The simple version is more alarming but throws away the trend signal that makes the Watchlist layer valuable. This is a real tradeoff, not a case of one formula being wrong.""")

md("""## 7. One-Layer Counterfactual — What If the Watchlist (Layer 5) Didn't Exist?""")

code("""# Would DS-003's problem still be visible using only control_test_results (Layer 3), no dq_watchlist?
conn.execute(\"\"\"
    SELECT dataset_id, COUNT(*) as tests, SUM(CASE WHEN status='Fail' THEN 1 ELSE 0 END) as fails
    FROM control_test_results WHERE dataset_id='DS-003' GROUP BY dataset_id
\"\"\").df()""")

code("""# Would DS-012's false-positive trend signal exist without dq_watchlist?
# Layer 3's table has no null-rate or duplicate-rate concept at all - list its columns to prove it.
cols = conn.execute("DESCRIBE control_test_results").df()['column_name'].tolist()
print("control_test_results columns:", cols)
print("any null-rate column? ", [c for c in cols if 'null' in c.lower()])
print("any duplicate-rate column?", [c for c in cols if 'dup' in c.lower()])""")

md("""**Result:** DS-003's 100%-fail problem is directly visible in `control_test_results` alone (150/150 fails) — Layer 3 (Detect) catches it without needing Layer 5 at all. But DS-012's false positive is a `dq_watchlist`-only concept: `control_test_results` has no null-rate or duplicate-rate columns whatsoever, so that entire signal — and the entire "too strict" failure mode found in Section 4 — would not exist without Layer 5. This distinguishes what the Watchlist layer uniquely contributes (trend detection on dimensions Layer 3 doesn't test at all) from what's redundant with Detect (raw failure visibility, which Layer 3 already provides).""")

md("""## 8. Named Limitations (In Code)

What this notebook's analysis can and cannot confirm, demonstrated directly rather than just asserted in prose.""")

code("""conn.execute("SELECT COUNT(*) as watchlist_row_count FROM dq_watchlist").df()""")

md("""`dq_watchlist` has exactly **13 rows — one per dataset, a point-in-time snapshot**, not a dated daily history. This is direct proof (not an assertion) that no query against this warehouse can backtest a claim like "flagged N days before failure" — there is no historical watchlist-status-by-date to diff against a later exception date.

**What this analysis cannot confirm:**
- A specific backtested early-warning lead time (the data structurally doesn't support it — see above).
- A real false-positive rate for the watchlist (no ground-truth "this alert was wrong" label exists in this warehouse).
- Any day-of-week SLA calendar effect (checked in `SQL_COMPARISON.md` Edge Case 3 — sample sizes too small to be conclusive).
- That any of these findings describe a real banking data quality problem. Every number in this notebook comes from `src/pipeline.py`'s synthetic data generator, seeded to the run date. The patterns found (DS-003, DS-012, the SLA inversion) are real behaviors of this specific framework and its scoring formulas — genuine design-methodology findings — but not discoveries about real production data.""")

nb['cells'] = cells

out_path = os.path.join(os.path.dirname(__file__), '..', 'notebooks', '01_governance_analysis.ipynb')
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    nbf.write(nb, f)
print(f"Wrote {out_path}")
